server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  profiles:
    active: dev
#    active: info
#    active: test
#    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'