server:
  port: 8001

spring:
  application:
    name: cloud-paymenthystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka     #单机版
  instance:
    instance-id: paymenthyxtrix8001
    prefer-ip-address: true



