server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group # 自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: 47.108.77.91:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
