server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka7001.com:7001//eureka,http://eureka7002.com:7002//eureka   #集群版
  instance:
    instance-id: orderFeign80  #Eureka中展示为实例名称
    prefer-ip-address: true  #Eureka中当鼠标移动到实例中显示ip信息提示
spring:
  application:
    name: orderFeign80

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000

logging:
  level:
    com.dcsyun.springcloud.service.*: debug

