server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.77.91:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource:
        ds2:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
#            dataId: ${spring.application.name}
#            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


service-url:
  nacos-user-service: http://nacos-payment-provider

#对Feign的支持
feign:
  sentinel:
    enabled: true