server:
  port: 83
spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.162:1111 #47.108.77.91:8848

service-url:
  nacos-user-service: http://nacos-payment-provider


